// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnqpFrzS0b1Tw-7VThszJXMwDHLpx_gf4',
    appId: '1:1071291420608:web:f439c75150a953e52a8225',
    messagingSenderId: '1071291420608',
    projectId: 'shopbiz-fc741',
    authDomain: 'shopbiz-fc741.firebaseapp.com',
    storageBucket: 'shopbiz-fc741.appspot.com',
    measurementId: 'G-NE971YR2WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASne1x0NIH6G_8gOc3fB_YZME46ohPW1c',
    appId: '1:1071291420608:android:3ce8df5cf31c12ff2a8225',
    messagingSenderId: '1071291420608',
    projectId: 'shopbiz-fc741',
    storageBucket: 'shopbiz-fc741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy3sB-X0NKz3mVBsqROOFR_qFroS0dVNE',
    appId: '1:1071291420608:ios:ebea5327680568e62a8225',
    messagingSenderId: '1071291420608',
    projectId: 'shopbiz-fc741',
    storageBucket: 'shopbiz-fc741.appspot.com',
    androidClientId: '1071291420608-c05mt8j8r2msrmq7k0cvlo81e044h46q.apps.googleusercontent.com',
    iosClientId: '1071291420608-1dhv2de4oo18a830rt6q11r78vr5l2a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy3sB-X0NKz3mVBsqROOFR_qFroS0dVNE',
    appId: '1:1071291420608:ios:ebea5327680568e62a8225',
    messagingSenderId: '1071291420608',
    projectId: 'shopbiz-fc741',
    storageBucket: 'shopbiz-fc741.appspot.com',
    androidClientId: '1071291420608-c05mt8j8r2msrmq7k0cvlo81e044h46q.apps.googleusercontent.com',
    iosClientId: '1071291420608-1dhv2de4oo18a830rt6q11r78vr5l2a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
